# Generated by Django 5.1.2 on 2025-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/albums/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/artists/'),
        ),
    ]
